import type { Metadata } from "next";
import { Header, Footer,Navbar } from "@jeong-hangyeol/jjabda-ui";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="h-full"
    >
      <body className="min-h-full flex flex-col">
          <Header />
          <Navbar
            color="#5383E8"
            links={[
              { href: "/", label: "홈" },
              { href: "/automatic-lotto", label: "로또 자동생성기" },
            ]}
          />
          <main className="flex flex-1 flex-col">{children}</main>
          <Footer />
        </body>
    </html>
  );
}
